aliases: []
creation_timestamp: 1759069779467
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1759069779467
metrics: null
model_id: m-205cb28cbe754bf89a7e783d66b7ec3a
name: commute-weather-ridge_enhanced
params: null
run_id: 5933cbd572b345d7bab86696e7d29e2f
run_link: null
source: models:/m-205cb28cbe754bf89a7e783d66b7ec3a
status: READY
status_message: null
storage_location: file:///Users/seoyeonmun/commute-weather-self-mlops/test_mlruns/684928457309897534/models/m-205cb28cbe754bf89a7e783d66b7ec3a/artifacts
user_id: null
version: 1
