aliases: []
creation_timestamp: 1759069781830
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1759069781830
metrics: null
model_id: m-b9c0c5b710f14a5984548e8eb419b1c6
name: commute-weather-gradient_boosting_enhanced
params: null
run_id: 203569a511e142328c6d1f36c6134a49
run_link: null
source: models:/m-b9c0c5b710f14a5984548e8eb419b1c6
status: READY
status_message: null
storage_location: file:///Users/seoyeonmun/commute-weather-self-mlops/test_mlruns/684928457309897534/models/m-b9c0c5b710f14a5984548e8eb419b1c6/artifacts
user_id: null
version: 1
