aliases: {}
creation_timestamp: 1759069781829
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1759069781830
name: commute-weather-gradient_boosting_enhanced
