aliases: []
creation_timestamp: 1759069780648
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1759069780648
metrics: null
model_id: m-db8678205d764a19b28d3b804e791664
name: commute-weather-random_forest_enhanced
params: null
run_id: 87f589a147b7460383cd534c9857b22c
run_link: null
source: models:/m-db8678205d764a19b28d3b804e791664
status: READY
status_message: null
storage_location: file:///Users/seoyeonmun/commute-weather-self-mlops/test_mlruns/684928457309897534/models/m-db8678205d764a19b28d3b804e791664/artifacts
user_id: null
version: 1
